backend:
  name: github
  repo: roshankayastha/bajralaw
  branch: master
  base_url: https://sveltia-cms-auth.roshankayastha8.workers.dev

local_backend: true

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "content"
    label: "Website Content"
    delete: false
    files:
      - name: "articles"
        label: "News & Publications"
        file: "assets/articles.json"
        format: "json"
        fields:
          - name: "articles"
            label: "Articles"
            label_singular: "Article"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Publish Date", name: "date", widget: "string" }
              - { label: "Category", name: "category", widget: "string" }
              - { label: "Image URL", name: "image", widget: "string" }
              - { label: "Excerpt", name: "excerpt", widget: "text" }
              - { label: "Content", name: "content", widget: "markdown" }
      - name: "team"
        label: "Meet Our Team"
        file: "assets/team.json"
        format: "json"
        fields:
          - name: "members"
            label: "Team Members"
            label_singular: "Team Member"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Full Name", name: "name", widget: "string" }
              - { label: "Role / Title", name: "role", widget: "string" }
              - { label: "Photo URL", name: "image", widget: "image" }
              - { label: "Short Bio", name: "bio", widget: "text" }
              - { label: "Contact Email", name: "email", widget: "string" }
